cvm-version: 0.14.7
cpus: 2
memory: 8192

containers:
  - name: "waddle"
    image: "ghcr.io/nchapman/waddle@sha256:627b38c5eba664a7c70ecc917913f319fb8e71e8cfadfa17087aa925236d0655"
    env:
      - PORT: "8080"
      - NODE_ENV: "production"

shim:
  upstream-port: 8080
  paths:
    - /*
