cvm-version: 0.14.7
cpus: 2
memory: 8192

containers:
  - name: "waddle"
    image: "ghcr.io/nchapman/waddle@sha256:d7e75f7a5f17a0ed1fc7e566e3e9851616da9c5eed9005d73ea68c1256209038"
    env:
      - PORT: "8080"
      - NODE_ENV: "production"

shim:
  upstream-port: 8080
  paths:
    - /*
